# Generated by Django 5.0.2 on 2024-03-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='timestamps',
            new_name='created_at',
        ),
    ]
