# Generated by Django 5.0.2 on 2024-03-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0002_rename_timestamps_customer_created_at'),
        ('restaurant_app', '0031_rename_timestamps_menuitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='restaurant_app.restaurant'),
        ),
    ]
