# Generated by Django 5.0.2 on 2024-03-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0003_customer_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
