# Generated by Django 5.0.1 on 2024-01-21 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_remove_admin_id'),
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='account',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth_app.account'),
            preserve_default=False,
        ),
    ]
