# Generated by Django 5.0.1 on 2024-01-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_admin_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='account',
        ),
        migrations.AddField(
            model_name='admin',
            name='id',
            field=models.BigAutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
