# Generated by Django 5.0.1 on 2024-01-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_admin_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='restaurant',
        ),
    ]
