# Generated by Django 5.0.1 on 2024-01-23 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_remove_admin_restaurant'),
        ('restaurant_app', '0003_remove_restaurant_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='restaurant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.restaurant'),
        ),
    ]
