# Generated by Django 5.0.1 on 2024-01-23 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_admin_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
    ]
