# Generated by Django 5.0.1 on 2024-01-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_remove_admin_email_remove_admin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
