# Generated by Django 5.0.1 on 2024-01-28 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_admin_phone_number'),
        ('payment_app', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_app.subscription'),
        ),
    ]
