# Generated by Django 5.0.2 on 2024-02-28 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_admin_is_subscribed_admin_subscription'),
        ('payment_app', '0002_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_app.subscription'),
        ),
    ]
