# Generated by Django 5.0.2 on 2024-03-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_alter_admin_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='timestamps',
            new_name='created_at',
        ),
    ]
