# Generated by Django 5.0.2 on 2024-03-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_rename_timestamps_admin_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
