# Generated by Django 5.0.2 on 2024-03-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_adminadress_admindoc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admindoc',
            old_name='buisness_register',
            new_name='business_register',
        ),
    ]
