# Generated by Django 5.0.2 on 2024-03-12 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_rename_adress_admindoc_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindoc',
            name='admin',
            field=models.ForeignKey(default=51, on_delete=django.db.models.deletion.CASCADE, related_name='admin_docs', to='admin_app.admin'),
            preserve_default=False,
        ),
    ]
