# Generated by Django 5.0.2 on 2024-03-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0016_admindoc_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='has_submitted_docs',
            field=models.BooleanField(default=False),
        ),
    ]
