# Generated by Django 5.0.1 on 2024-03-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0017_admin_has_submitted_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindoc',
            name='phone',
            field=models.CharField(default='010000'),
            preserve_default=False,
        ),
    ]
