# Generated by Django 5.0.1 on 2024-03-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0017_admin_has_submitted_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admindoc',
            name='phone',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admindoc',
            name='superadmin_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
