# Generated by Django 5.0.1 on 2024-03-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0018_admindoc_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindoc',
            name='phone',
            field=models.CharField(blank=True, null=True),
        ),
    ]
