# Generated by Django 5.0.1 on 2024-03-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0019_alter_admindoc_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admindoc',
            name='superadmin_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
