# Generated by Django 5.0.1 on 2024-03-19 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0020_admin_is_rejected_admindoc_superadmin_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admindoc',
            name='phone',
        ),
    ]
