# Generated by Django 5.0.1 on 2024-03-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0021_remove_admindoc_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindoc',
            name='phone',
            field=models.CharField(blank=True, null=True),
        ),
    ]
