# Generated by Django 5.0.2 on 2024-03-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='timestamps',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='timestamps',
            new_name='created_at',
        ),
    ]
