# Generated by Django 5.0.1 on 2024-01-21 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart_app', '0001_initial'),
        ('customer_app', '0001_initial'),
        ('delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
                ('house_number', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('restaurant_vat', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pick_time', models.DateTimeField(blank=True, null=True)),
                ('coupon_code', models.CharField(blank=True, max_length=255, null=True)),
                ('order_mode', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery'), ('reservation', 'Reservation')], max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_app.customer')),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order_app.deliveryaddress')),
                ('delivery_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.deliveryman')),
                ('menu_items', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart_app.cart')),
            ],
        ),
    ]
