# Generated by Django 5.0.2 on 2024-02-27 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='menu_items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_mode',
        ),
    ]
