# Generated by Django 5.0.2 on 2024-03-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_remove_order_menu_items_remove_order_order_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='timestamps',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='timestamps',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='orderinvoice',
            old_name='timestamps',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='timestamps',
            new_name='created_at',
        ),
    ]
