# Generated by Django 5.0.1 on 2024-03-23 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0012_remove_cart_service'),
        ('order_app', '0004_rename_timestamps_deliveryaddress_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_man',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart_app.cart'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DeliveryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('post_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('lane', models.CharField(max_length=255)),
                ('street_name', models.CharField(max_length=255)),
                ('house_number', models.CharField(blank=True, max_length=255, null=True)),
                ('floor', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order_app.deliverydetails'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DeliveryAddress',
        ),
    ]
