# Generated by Django 5.0.1 on 2024-03-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_remove_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_way',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('cash', 'Cash on Delivery'), ('paypal', 'PayPal')], max_length=20),
        ),
    ]
