# Generated by Django 5.0.1 on 2024-03-25 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0006_alter_order_payment_way'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverydetails',
            name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order_app.deliverydetails'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
