# Generated by Django 5.0.1 on 2024-03-25 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0012_remove_cart_service'),
        ('order_app', '0007_remove_deliverydetails_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart_app.cart'),
        ),
    ]
