# Generated by Django 5.0.1 on 2024-03-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0008_alter_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
