# Generated by Django 5.0.1 on 2024-03-26 06:56

import order_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0010_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected_extra_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='selected_type_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.JSONField(blank=True, encoder=order_app.models.DecimalEncoder, null=True),
        ),
    ]
