# Generated by Django 5.0.1 on 2024-03-26 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0011_order_selected_extra_ids_order_selected_type_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='selected_extra_ids',
        ),
        migrations.RemoveField(
            model_name='order',
            name='selected_type_ids',
        ),
    ]
