# Generated by Django 5.0.1 on 2024-03-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0016_order_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_intent_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
