# Generated by Django 5.0.1 on 2024-03-30 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0017_order_payment_intent_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_status',
            new_name='payment_order_status',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_or_pickup_time',
            new_name='selected_order_time',
        ),
    ]
