# Generated by Django 5.0.1 on 2024-03-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0018_rename_order_status_order_payment_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='in-progress', max_length=255),
        ),
    ]
