# Generated by Django 5.0.1 on 2024-03-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0019_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_left',
            field=models.DurationField(blank=True, help_text='Countdown time until order delivery', null=True),
        ),
    ]
