# Generated by Django 5.0.1 on 2024-03-31 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0020_order_time_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_intent_secret',
            field=models.CharField(blank=True, default=datetime.timedelta(seconds=1200), max_length=255, null=True),
        ),
    ]
