# Generated by Django 5.0.1 on 2024-03-31 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0021_alter_order_payment_intent_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_intent_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_left',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=1200), help_text='Countdown time until order delivery', null=True),
        ),
    ]
