# Generated by Django 5.0.1 on 2024-01-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_admin_user'),
        ('auth_app', '0002_remove_account_groups_and_more'),
        ('customer_app', '0003_remove_customer_account_customer_id_customer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
