# Generated by Django 5.0.1 on 2024-02-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0001_initial'),
        ('restaurant_app', '0013_alter_restaurant_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='offers',
            new_name='Offer',
        ),
    ]
