# Generated by Django 5.0.2 on 2024-03-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_remove_offer_menu_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='timestamps',
            new_name='created_at',
        ),
    ]
