# Generated by Django 5.0.2 on 2024-02-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0004_cartitem_total_price_after_discount_and_more'),
        ('customer_app', '0001_initial'),
        ('restaurant_app', '0030_alter_menuitemtypeitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_extra_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selected_type_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('customer', 'restaurant')},
        ),
    ]
