# Generated by Django 5.0.2 on 2024-02-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0006_alter_cart_unique_together'),
        ('customer_app', '0001_initial'),
        ('restaurant_app', '0030_alter_menuitemtypeitem_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('customer', 'restaurant')},
        ),
    ]
