# Generated by Django 5.0.2 on 2024-03-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0008_cart_order_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
