# Generated by Django 5.0.2 on 2024-03-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0009_cart_delivery_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='timestamps',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='timestamps',
            new_name='created_at',
        ),
    ]
