# Generated by Django 5.0.2 on 2024-03-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0010_rename_timestamps_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price_after_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
