# Generated by Django 5.0.2 on 2024-03-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0011_cartitem_price_after_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='service',
        ),
    ]
