# Generated by Django 5.0.2 on 2024-03-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0002_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='timestamps',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='paymentway',
            old_name='timestamps',
            new_name='created_at',
        ),
    ]
