# Generated by Django 5.0.1 on 2024-01-15 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery_app', '0001_initial'),
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.order'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.deliveryman'),
        ),
        migrations.AddField(
            model_name='deliveryroute',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.delivery'),
        ),
    ]
