# Generated by Django 5.0.1 on 2024-01-15 09:32

import django.contrib.postgres.fields
import django.db.models.deletion
import restaurant_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=restaurant_app.models.category_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=list, max_length=100, null=True), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='OrderMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to=restaurant_app.models.restaurant_logo_path)),
                ('state', models.BooleanField()),
                ('freeDelivery', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('open_in', models.CharField(max_length=5)),
                ('close_in', models.CharField(max_length=5)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('minimum_order', models.DecimalField(decimal_places=2, max_digits=5)),
                ('delivery_time', models.IntegerField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('categories', models.ManyToManyField(to='restaurant_app.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_app.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_app.country')),
                ('order_modes', models.ManyToManyField(blank=True, to='restaurant_app.ordermode')),
            ],
        ),
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.category')),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.ingredients')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
                ('table_number', models.IntegerField()),
                ('size', models.IntegerField()),
                ('table_status', models.BooleanField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.restaurant')),
            ],
        ),
    ]
