# Generated by Django 5.0.1 on 2024-01-23 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_remove_admin_restaurant'),
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='admin',
            field=models.OneToOneField(default='5', on_delete=django.db.models.deletion.CASCADE, to='admin_app.admin'),
            preserve_default=False,
        ),
    ]
