# Generated by Django 5.0.1 on 2024-01-15 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='ingredients',
        ),
    ]
