# Generated by Django 5.0.1 on 2024-01-23 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_restaurant_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='admin',
        ),
    ]
