# Generated by Django 5.0.1 on 2024-01-27 12:59

import restaurant_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_remove_restaurant_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermode',
            name='name',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup')], max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='close_in',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='freeDelivery',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(null=True, upload_to=restaurant_app.models.restaurant_logo_path),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='minimum_order',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='open_in',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
