# Generated by Django 5.0.1 on 2024-01-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_menuitem_ingredients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredients',
        ),
    ]
