# Generated by Django 5.0.1 on 2024-01-15 13:35

import restaurant_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0004_delete_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='background',
            field=models.ImageField(null=True, upload_to=restaurant_app.models.restaurant_background_path),
        ),
    ]
