# Generated by Django 5.0.1 on 2024-01-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0005_alter_ordermode_name_alter_restaurant_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='categories',
            field=models.ManyToManyField(blank=True, to='restaurant_app.category'),
        ),
    ]
