# Generated by Django 5.0.1 on 2024-01-17 12:16

import restaurant_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0005_restaurant_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(null=True, upload_to=restaurant_app.models.menuitem_image_path),
        ),
    ]
