# Generated by Django 5.0.1 on 2024-01-28 14:38

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0007_remove_menuitem_price_menuitem_sizes_and_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='ingredients',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='sizes_and_prices',
            field=django_jsonform.models.fields.ArrayField(base_field=django_jsonform.models.fields.JSONField(), default=list, size=None),
        ),
    ]
