# Generated by Django 5.0.1 on 2024-02-05 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0011_restaurant_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='freeDelivery',
            new_name='free_delivery',
        ),
    ]
