# Generated by Django 5.0.1 on 2024-02-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0012_rename_freedelivery_restaurant_free_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
