# Generated by Django 5.0.2 on 2024-02-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0013_alter_restaurant_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='order_modes',
        ),
        migrations.DeleteModel(
            name='OrderMode',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='order_modes',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('takeaway', 'Takeaway'), ('dine_in', 'Dine-in')], null=True),
        ),
    ]
