# Generated by Django 5.0.2 on 2024-02-13 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_remove_offer_menu_item'),
        ('restaurant_app', '0015_category_offer_menuitem_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='offer',
        ),
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.category')),
                ('offer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers_app.offer')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.restaurant')),
            ],
            options={
                'unique_together': {('restaurant', 'category')},
            },
        ),
    ]
