# Generated by Django 5.0.2 on 2024-02-14 08:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0017_alter_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantcategory',
            name='mame',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantcategory',
            name='tax',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='sizes_and_prices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, null=True, size=None),
        ),
    ]
