# Generated by Django 5.0.2 on 2024-02-14 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0018_restaurantcategory_mame_restaurantcategory_tax_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantcategory',
            old_name='mame',
            new_name='name',
        ),
    ]
