# Generated by Django 5.0.2 on 2024-02-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0019_rename_mame_restaurantcategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='categories',
        ),
    ]
