# Generated by Django 5.0.2 on 2024-02-17 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0020_remove_restaurant_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurant_app.restaurantcategory'),
        ),
    ]
