# Generated by Django 5.0.2 on 2024-02-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0021_alter_menuitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeAndPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='sizes_and_prices',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sizes_and_prices',
            field=models.ManyToManyField(to='restaurant_app.sizeandprice'),
        ),
    ]
