# Generated by Django 5.0.2 on 2024-02-17 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0022_sizeandprice_remove_menuitem_sizes_and_prices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='sizes_and_prices',
        ),
        migrations.AddField(
            model_name='sizeandprice',
            name='menu_item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.menuitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurant_app.restaurantcategory'),
        ),
    ]
