# Generated by Django 5.0.2 on 2024-02-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0023_remove_menuitem_sizes_and_prices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='order_modes',
        ),
    ]
