# Generated by Django 5.0.2 on 2024-02-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0024_remove_restaurant_order_modes'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='order_modes',
            field=models.JSONField(default=list),
        ),
    ]
