# Generated by Django 5.0.2 on 2024-02-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0025_restaurant_order_modes'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
