# Generated by Django 5.0.2 on 2024-02-19 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0026_restaurantcategory_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='extras',
            field=models.ManyToManyField(blank=True, to='restaurant_app.menuitemextra'),
        ),
        migrations.CreateModel(
            name='MenuItemExtraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant_app.menuitemextra')),
            ],
        ),
    ]
