# Generated by Django 5.0.2 on 2024-03-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0030_alter_menuitemtypeitem_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='timestamps',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='menusection',
            old_name='timestamps',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='timestamps',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='restaurantregion',
            old_name='timestamps',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='restauranttable',
            old_name='timestamps',
            new_name='created_at',
        ),
    ]
