# Generated by Django 5.0.1 on 2024-03-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0031_rename_timestamps_menuitem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_time',
            field=models.IntegerField(default=30, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
