# Generated by Django 5.0.1 on 2024-03-20 09:22

import django.db.models.deletion
import restaurant_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0018_admin_is_rejected_admindoc_phone_and_more'),
        ('restaurant_app', '0032_alter_restaurant_delivery_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregoryAdminRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('requseted_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to=restaurant_app.models.category_admin_request_image_path)),
                ('is_accepted', models.BooleanField(default='False')),
                ('requseted_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_app.admin')),
            ],
        ),
    ]
