# Generated by Django 5.0.1 on 2024-03-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0018_admin_is_rejected_admindoc_phone_and_more'),
        ('restaurant_app', '0033_caregoryadminrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaregoryAdminRequest',
            new_name='CategoryAdminRequest',
        ),
    ]
