# Generated by Django 5.0.1 on 2024-03-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0034_rename_caregoryadminrequest_categoryadminrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryadminrequest',
            old_name='requseted_by',
            new_name='requested_by',
        ),
    ]
