# Generated by Django 5.0.1 on 2024-03-20 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0018_admin_is_rejected_admindoc_phone_and_more'),
        ('restaurant_app', '0035_rename_requseted_by_categoryadminrequest_requested_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryadminrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.admin'),
        ),
    ]
