# Generated by Django 5.0.1 on 2024-03-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0036_alter_categoryadminrequest_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryadminrequest',
            name='is_rejected',
            field=models.BooleanField(default='False'),
        ),
    ]
