# Generated by Django 5.0.1 on 2024-03-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0037_categoryadminrequest_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryadminrequest',
            name='superadmin_notes',
            field=models.TextField(null=True),
        ),
    ]
