# Generated by Django 5.0.1 on 2024-03-24 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0038_categoryadminrequest_superadmin_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='categoryadminrequest',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['created_at']},
        ),
    ]
