# Generated by Django 5.0.1 on 2024-04-06 11:39

import restaurant_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0039_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantcategory',
            name='image',
            field=models.ImageField(null=True, upload_to=restaurant_app.models.restaurant_category_image_path),
        ),
    ]
