# Generated by Django 5.0.1 on 2024-04-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0040_restaurantcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='free_delivery',
        ),
    ]
