# Generated by Django 5.0.1 on 2024-04-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0042_restaurant_free_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='free_delivery_from',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, null=True),
        ),
    ]
