# Generated by Django 5.0.1 on 2024-05-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0047_alter_menuitem_extras_alter_menuitem_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='extras',
            field=models.ManyToManyField(blank=True, to='restaurant_app.menuitemextra'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='types',
            field=models.ManyToManyField(blank=True, to='restaurant_app.menuitemtype'),
        ),
    ]
