from rest_framework import serializers
from .models import Offer


class OfferCreateSerializer(serializers.ModelSerializer):
    class Meta:
        model = Offer
        exclude = ['id']  # Exclude the id field since it's autogenerated

class OfferUpdateSerializer(serializers.ModelSerializer):
    class Meta:
        model = Offer
        fields = '__all__'

class OfferDeleteSerializer(serializers.ModelSerializer):
    class Meta:
        model = Offer
        fields = ['id']  # Only need the id for deletion