# Generated by Django 5.0.1 on 2024-04-14 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0004_deliveryrating_order_qualityrating_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryrating',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='qualityrating',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='totalrating',
            name='restaurant',
        ),
    ]
