# Generated by Django 5.0.1 on 2024-04-14 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0040_restaurantcategory_image'),
        ('review_app', '0006_totalrating_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalrating',
            name='order',
        ),
        migrations.AddField(
            model_name='totalrating',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.restaurant'),
        ),
    ]
