# Generated by Django 5.0.1 on 2024-04-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0007_remove_totalrating_order_totalrating_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityrating',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
