# Generated by Django 5.0.1 on 2024-04-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0008_qualityrating_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-04-18 14:30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualityrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-04-18 14:30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-04-18 14:30'),
            preserve_default=False,
        ),
    ]
